version: "3.6"

services:
  iris:
    image: store/intersystems/iris:2019.1.0.511.0-community
    entrypoint: ["bash", "-c", "cp /run/secrets/password /password && ./iris-main --password-file /password"]
    ports:
     - "52773:52773"
     - "51773:51773"
    secrets:
      - password
secrets:
  password:
    external: true