version: "3.6"

services:
  iris:
    image: intersystems/iris:2019.1.0.510.0-community
    command: --password-file /run/secrets/password
    ports:
     - "52773:52773"
     - "51773:51773"
    secrets:
      - password
secrets:
  password:
    file: ./password.txt