version: "3.6"

services:
  iris:
    image: store/intersystems/iris:2019.1.0.511.0-community
    volumes:
     - data:/dur
    environment:
     - ISC_DATA_DIRECTORY=/dur
    ports:
     - "52773:52773"
     - "51773:51773"
volumes:
  data: