version: '3'

services:
  db:
    image: mariadb
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: mydb
volume:
  data: