version: '3'

services:
  db:
    image: mariadb
    secrets:
      - password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dba
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/password
      MYSQL_PASSWORD_FILE: /run/secrets/password
secrets:
   password:
     file: ./password.txt