version: '3.3'
services:
    postgres:
        image: postgres
        container_name: postgres
        volumes:
          - data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "my_db"
        ports:
          - "5432:5432"
volumes:
  data: